[package]
name = "physics-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
gl = "0.14.0"
mint = "0.5.9"
nalgebra-glm = "0.18.0"
rand = "0.8.5"
sdl2 = "0.35.2"
wgpu = "0.17.1"
winit = "0.28.7"
