[package]
name = "physics-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.14.0"
cfg-if = "1.0.0"
env_logger = "0.10.0"
futures = "0.3.28"
gl = "0.14.0"
mint = "0.5.9"
naga = "0.13.0"
nalgebra-glm = "0.18.0"
rand = "0.8.5"
sdl2 = "0.35.2"
wgpu = { version="0.17.1", features=["glsl", "expose-ids"] }
winit = "0.28.7"
